<a href="https://colab.research.google.com/github/lincolngadea/ia_machine_learning/blob/main/sample_k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random
import plotly.express as px

In [3]:
idades_x = [random.randint(18,65) for _ in range(100)]
salarios_y = [random.randint(1800,5000) for _ in range(100)]

In [4]:
grafico = px.scatter(x=idades_x, y=salarios_y)
grafico.show()
#

In [5]:
base_salario = np.array([[idade, salario] for idade, salario in zip(idades_x, salarios_y)])

In [6]:
base_salario

array([[  34, 2985],
       [  54, 3018],
       [  34, 3960],
       [  51, 2748],
       [  30, 3822],
       [  27, 4802],
       [  40, 2131],
       [  47, 4585],
       [  56, 2169],
       [  63, 1834],
       [  51, 4070],
       [  22, 4253],
       [  43, 3971],
       [  34, 2946],
       [  36, 2598],
       [  18, 3633],
       [  51, 4287],
       [  43, 2537],
       [  44, 4133],
       [  42, 3678],
       [  31, 2732],
       [  57, 4993],
       [  24, 4581],
       [  46, 3174],
       [  41, 3724],
       [  51, 3423],
       [  63, 2150],
       [  60, 3004],
       [  31, 4202],
       [  58, 4799],
       [  38, 4158],
       [  43, 2682],
       [  57, 1815],
       [  29, 2370],
       [  62, 3374],
       [  20, 4425],
       [  41, 2665],
       [  39, 4376],
       [  28, 3602],
       [  56, 2811],
       [  56, 4048],
       [  33, 2916],
       [  35, 3817],
       [  52, 3864],
       [  27, 2205],
       [  46, 4180],
       [  38, 4141],
       [  38,

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)

In [9]:
base_salario

array([[-0.64305432, -0.47109806],
       [ 0.93499309, -0.43222956],
       [-0.64305432,  0.6772896 ],
       [ 0.69828598, -0.7502446 ],
       [-0.9586638 ,  0.51474857],
       [-1.19537091,  1.6690254 ],
       [-0.1696401 , -1.47696787],
       [ 0.3826765 ,  1.41343553],
       [ 1.09279783, -1.4322102 ],
       [ 1.64511442, -1.82678442],
       [ 0.69828598,  0.80685128],
       [-1.58988276,  1.02239481],
       [ 0.06706701,  0.69024577],
       [-0.64305432, -0.51703357],
       [-0.48524958, -0.92691963],
       [-1.90549224,  0.29213804],
       [ 0.69828598,  1.06244115],
       [ 0.06706701, -0.99876747],
       [ 0.14596939,  0.88105479],
       [-0.01183536,  0.34514055],
       [-0.87976143, -0.76908994],
       [ 1.1717002 ,  1.8939916 ],
       [-1.43207802,  1.4087242 ],
       [ 0.30377413, -0.24848753],
       [-0.09073773,  0.39932089],
       [ 0.69828598,  0.04479301],
       [ 1.64511442, -1.45458904],
       [ 1.40840731, -0.44871923],
       [-0.87976143,

In [10]:
from sklearn.cluster import KMeans

In [11]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [12]:
#Calcula os centroides
centroides_salario = kmeans_salario.cluster_centers_
centroides_salario

array([[-1.00924224, -0.13925103],
       [ 0.88161796, -0.7241937 ],
       [ 0.34760878,  1.11308799]])

In [13]:
#Apresenta a escala inversa dos dados treinados
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)

array([[  29.35897436, 3266.74358974],
       [  53.32352941, 2770.11764706],
       [  46.55555556, 4330.        ]])

In [14]:
# Define a classificação do agrupamento dos dados por meio de rotulos
rotulos_salario = kmeans_salario.labels_
rotulos_salario

array([0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 2, 2, 0, 2,
       0, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 0, 0, 2,
       0, 2, 2, 0, 0, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0,
       0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 2,
       0, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1], dtype=int32)

In [18]:
import plotly.graph_objects as go

In [19]:
# Apresenta o gráfico do resultado
grafico1 = px.scatter(x=base_salario[:,0], y=base_salario[:,1], color=rotulos_salario)
grafico2 = px.scatter(x=centroides_salario[:,0], y=centroides_salario[:,1], color=['red', 'green', 'blue'], size=[8,8,8])
grafico3 = go.Figure(data=grafico1.data + grafico2.data)
grafico3.show()